---
driver:
  network:
    - ["private_network", {ip: "192.168.0.160"}]
  name: vagrant
  vm_hostname: verdaccio-vagrant

driver_config:
  require_chef_omnibus: true
  customize:
    memory: 512
    natdnsproxy1: 'on'
    natdnshostresolver1: 'on'

platforms:
- name: debian-8.5

provisioner:
  name: chef_zero

suites:
- name: default
  run_list:
    - recipe[verdaccio]
  attributes:
    verdaccio:
      listen: :4873
